<!doctype html>
<html lang="fr">

<head>
    <style>
        /*@import url('https://fonts.googleapis.com/'); FONTS GOOGLE */
    </style>
    <meta charset="UTF-8">
    <title>Bienvenue au Normandie !</title>
    <link rel="stylesheet" href="./assets/css/style.css" type="text/css" />
    <meta name="viewport" content="width=device-width,initial-scale=1" />
</head>

<body>
    
    <header>
        
        <div>
            <div>
                <div>
                    <img src="../assets/images/Flag_of_Normandie1.svg" alt="Léopard du drapeau normand"></img>
                </div>
                
                <h1>Le NORMANDIE</h1>
                
                <div>
                    <img src="../assets/images/Flag_of_Normandie.svg" alt="Léopard du drapeau normand"></img>
                </div>
            </div>
            
            <div>
                <h2>10 rue Custine, Paris XVIII</h2>
            </div>
        </div>
        
        <nav>
            
        </nav>
        
    </header>